apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-portfoilo-deployment
spec:
  replicas: 10
  selector:
    matchLabels:
      app: my-profile
  template:
    metadata:
      labels:
        app: my-profile
    spec:
      containers:
        - name: my-profile
          image: rohitgitte01/devops-portfolio:v1
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "120Mi"
            limits:
              cpu: "200m"
              memory: "130Mi"

