apiVersion: v1
kind: Service
metadata:
  name: devops-portfolio-service
  labels:
    app: my-profile
    app.kubernetes.io/name: devops-portfolio
spec:
  type: NodePort        # Use NodePort for Minikube/local
  selector:
    app: my-profile     # Must match Deployment labels
  ports:
    - name: http
      port: 80          # Service port (inside cluster)
      targetPort: 3000  # Container port
      nodePort: 30017   # Optional (30000â€“32767)


